### ISSUE TITLE
parquet-mr mvn install error

### ISSUE THREAD

**Issue by nkoutroumanis** [MajidSas/spatialParquet#1]
I get an error when i'm running `mvn install` in the parquet-mr folder. 
Is there a source available to download it?

Thank you,
Nikos

**Comment by MajidSas** [comment]
Hi Nikos,

What is the error message that you get?

It requires thrift@0.16.0 as mentioned in its readme, so make sure it is installed.

For your convenience, I uploaded compiled packages that include all dependencies here:
https://drive.google.com/drive/folders/1GJC7YFV8wqNUsKqNQQHNUfjut3_t_Odh?usp=share_link

Link one of them to your project, and import all classes using "edu.ucr.cs.bdlab.spatialParquet.*" and use it like in 
https://github.com/MajidSas/spatialParquet/blob/main/src/main/java/edu/ucr/cs/bdlab/spatialParquet/Main.java

**Comment by nkoutroumanis** [comment]
Actually in the second bullet in the readme file it is stated "**Go to the folder parquet-mr and run mvn install**". I cd to the parquet-mr folder but the folder is empty, so the mvn install command cannot run. Is it feasible to get this folder?

**Comment by MajidSas** [comment]
I wasn't aware of this. I uploaded it to a separate repo:
https://github.com/MajidSas/parquet-mr

You can check this commit for all the changes I added:
https://github.com/MajidSas/parquet-mr/commit/70d461125e476712b834d68bce102a8e2456c5a9

I'll change the instructions accordingly.

**Comment by nkoutroumanis** [comment]
Thank you Majid! :)

**Comment by badbye** [comment]
> I wasn't aware of this. I uploaded it to a separate repo: https://github.com/MajidSas/parquet-mr
> 
> You can check this commit for all the changes I added: [MajidSas/parquet-mr@70d4611](https://github.com/MajidSas/parquet-mr/commit/70d461125e476712b834d68bce102a8e2456c5a9)
> 
> I'll change the instructions accordingly.

@MajidSas I can not open this link [MajidSas/parquet-mr@70d4611](https://github.com/MajidSas/parquet-mr/commit/70d461125e476712b834d68bce102a8e2456c5a9), I guess you move it to https://github.com/MajidSas/parquet-mr-2/commit/70d461125e476712b834d68bce102a8e2456c5a9, right?

**Comment by MajidSas** [comment]
This is correct. I moved it to parquet-mr-2. You can also use the pre-compiled file I provided above. I plan to create a new version that doesn't require a modified parquet version. That's why I made this change. It'll also improve the read/write time. I haven't got the chance to sit and do it yet.

Let me know if this works for you at the moment.
